### ISSUE TITLE
TypeError at startup (MacOS) TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by pestikoko11** [abdeladim-s/subsai#108]
Hi guys, I'm getting this error when I'm trying to start the webUI. I installed all of the requirements and should encounter no issues with that. The error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/subsai", line 5, in <module>
    from subsai.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/subsai/__init__.py", line 1, in <module>
    from subsai.main import SubsAI, Tools
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/subsai/main.py", line 28, in <module>
    from subsai.configs import AVAILABLE_MODELS
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/subsai/configs.py", line 12, in <module>
    from subsai.models.whisperX_model import WhisperXModel
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/subsai/models/whisperX_model.py", line 16, in <module>
    import whisperx
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whisperx/__init__.py", line 1, in <module>
    from .transcribe import load_model
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whisperx/transcribe.py", line 10, in <module>
    from .asr import load_model
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whisperx/asr.py", line 13, in <module>
    from .vad import load_vad_model, merge_chunks
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whisperx/vad.py", line 9, in <module>
    from pyannote.audio import Model
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyannote/audio/__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyannote/audio/core/inference.py", line 37, in <module>
    from pyannote.audio.core.model import Model, Specifications
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyannote/audio/core/model.py", line 47, in <module>
    from pyannote.audio.core.task import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyannote/audio/core/task.py", line 38, in <module>
    from pyannote.database import Protocol
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyannote/database/__init__.py", line 36, in <module>
    from .registry import registry, LoadingMode
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyannote/database/registry.py", line 38, in <module>
    from .custom import create_protocol, get_init
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyannote/database/custom.py", line 66, in <module>
    from .loader import load_lst, load_trial
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyannote/database/loader.py", line 44, in <module>
    from spacy.tokens import Token
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/tokens/__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy/tokens/doc.pyx", line 36, in init spacy.tokens.doc
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/schemas.py", line 250, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 1134, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

Can anyone help me with this issue? Thanks a lot!

**Comment by abdeladim-s** [comment]
Hi @pestikoko11,

Seems there is something wrong with your Python installation. 
Can you try to install the project in a separate virtual environment ?

**Comment by pestikoko11** [comment]
> Hi @pestikoko11,
> 
> Seems there is something wrong with your Python installation. Can you try to install the project in a separate virtual environment ?

I am currently using python 3.10.0. Should I use another version for it? Seperate virtual environment as in a seperate folder or a different computer or a different python version? THanks a lot for your help.

**Comment by abdeladim-s** [comment]
A virtual env in Python is like an isolated lightweight Python environment separated from the system wide Python installation. 
 You can create one by running this command:
```shell
python -m venv /path/to/new/virtual/environment  # path to an an empty folder 
```
Make sure that the env is activated, and then install `subsai` on this env by following the same steps in the installation section. 

Let me know if you still find any difficulties.

**Comment by pestikoko11** [comment]
Thanks a lot for your help! That worked for me!
