### ISSUE TITLE
No module named 'whisper'

### ISSUE THREAD

**Issue by CorradoF** [abdeladim-s/subsai#143]
C:\WINDOWS\system32>subsai-webui
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\subsai-webui.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python310\lib\site-packages\subsai\__init__.py", line 1, in <module>
    from subsai.main import SubsAI, Tools
  File "C:\Program Files\Python310\lib\site-packages\subsai\main.py", line 28, in <module>
    from subsai.configs import AVAILABLE_MODELS
  File "C:\Program Files\Python310\lib\site-packages\subsai\configs.py", line 11, in <module>
    from subsai.models.faster_whisper_model import FasterWhisperModel
  File "C:\Program Files\Python310\lib\site-packages\subsai\models\faster_whisper_model.py", line 12, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'

I tried to reinstalling it with
pip install git+https://github.com/abdeladim-s/subsai
pip install pyproject.toml
pip install -r requirements.txt

not worked

**Comment by CorradoF** [comment]
Solved with
pip install git+https://github.com/openai/whisper.git

Now I have the problem ModuleNotFoundError: No module named ['julius'](url)

insane



![Screenshot 2024-09-05 225522](https://github.com/user-attachments/assets/8e69a0c1-aa34-4d9e-a2b1-55a6149d39fd)

**Comment by abdeladim-s** [comment]
@CorradoF, I think it's better to install the package in a separate virtual environment .. Installing it system wide might cause so many issues. 

Here are the steps
1. Create an empty folder 
2. open a terminal (cmd) in that folder 
1. create env `python -m venv subsai-env`
3. activate it `.\subsai-env\Scripts\activate`
4. Then install subsai : `pip install git+https://github.com/abdeladim-s/subsai`

Let me know if you find any issues during the installation.

**Comment by CorradoF** [comment]
After 2 hours I solved by using python 3.11, the 3.12 can't build the wheel even using rust, I don't have the screenshot about the error.

I don't know why, I'm on win10 when using venv with the command pip install git+https://github.com/abdeladim-s/subsai it doesn't download on venv folder and won't start anyway, it consumes C diskspace, so I had to delete all my python lib, deleted 3.12 3.11 3.10, tried them all as fresh installation and python 3.11 works
luckily every other program it works with requirement.txt and I can do the venv so I didn't lose much

**Comment by CorradoF** [comment]
Thanks for doing this amazing program :)

**Comment by abdeladim-s** [comment]
Oh yes, Python 3.12 is known to have many issues. 
But I'm glad it worked at the end!
Enjoy it :)

**Comment by absadiki** [comment]
@Conphyr, yes I believe it will work. Just avoid 3.12+
