### ISSUE TITLE
ROCm isnt supported

### ISSUE THREAD

**Issue by MidnightKittenCat** [abdeladim-s/subsai#67]
Is it possible to add ROCm support for amd gpus?

**Comment by abdeladim-s** [comment]
I think Pytorch supports ROCm, so it should be supported out of the box basically, but I didn't test it so I couldn't tell. 
You can give it a try, and let me know how it goes : 

1. create a new virtual environment.
2. install Pytorch ROCm compatible 
```shell
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
``` 
3. Then install `subsai` (as described in the README)

**Comment by MidnightKittenCat** [comment]
Doesn't seem like it, complains about cuda even if I've used the rocm one.

Seems to be hardcoded and there isnt a rocm version for the device type.

**Comment by MidnightKittenCat** [comment]
Pytorch does support rocm but this just complains about cuda libraries

**Comment by MidnightKittenCat** [comment]
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

**Comment by abdeladim-s** [comment]
> Doesn't seem like it, complains about cuda even if I've used the rocm one.
> 
> Seems to be hardcoded and there isnt a rocm version for the device type.

AFAIK, Pytorch is using cuda device name even for ROCm devices, so this is not a problem.

**Comment by abdeladim-s** [comment]
> Pytorch does support rocm but this just complains about cuda libraries

if it complains about cuda libraries, then maybe your GPU chip is not supported by Pytorch. 
Please make sure first that your GPU is supported from the [ROCm docs](https://rocm.docs.amd.com/en/latest/index.html), then run some [tests](https://rocm.docs.amd.com/en/latest/how_to/pytorch_install/pytorch_install.html#test-the-pytorch-installation) so you can know if it is working well or not!

**Comment by MidnightKittenCat** [comment]
It is indeed supported by rocm, like I said it's not pytorch that's complaining about it.

**Comment by MidnightKittenCat** [comment]
I've tried a conda env that didn't work, tried doing it globally also didn't work.

My GPU Chip is supported because I can use it on S.D. Next (Stable diffusion webui) just fine

**Comment by MidnightKittenCat** [comment]
Could you attempt to add ROCm to the device list and I can test it out for you or?

**Comment by abdeladim-s** [comment]
Weird! cause it should be working with the same device name of `cuda` as well! 
See this comment [here](https://github.com/pytorch/pytorch/issues/55223#issuecomment-812587373) as well. 
So you think this is bug in the package ? Do you have any idea where this is coming from ? what model are you trying to use ? what is the full error you are getting ?

**Comment by MidnightKittenCat** [comment]
I don’t think it’s an issue with PyTorch itself, it seems to me that the cuda device could be hardcoding cuda or something similar, as PyTorch with the same version on rocm works completely fine for me on other projects.

Perhaps take a look at the code and see if cuda is hardcoded.

**Comment by abdeladim-s** [comment]
Yes `cuda` is hardcoded if `torch.cuda.is_available() is True`.
To what a value should I change it so that ROCm device should be supported ?

**Comment by MidnightKittenCat** [comment]
I believe I've found the issue, "EXPORT HSA_OVERRIDE_GFX_VERSION=10.3.0" seems to of fixed the issue for me, so for future cases I'd redirect people to this fix and see if that works for them.

Unfortunately it's just AMD making it hard to identify their own hardware.

Sorry for the troubles <3

**Comment by MidnightKittenCat** [comment]
I would however like a feature that embeds the subtitles into the video, allowing us to download it afterwards (hopefully to get around the 200mb limit) 

Or even just making a flag to disable it. Unless there is one?

**Comment by abdeladim-s** [comment]
> I believe I've found the issue, "EXPORT HSA_OVERRIDE_GFX_VERSION=10.3.0" seems to of fixed the issue for me, so for future cases I'd redirect people to this fix and see if that works for them.
> 
> Unfortunately it's just AMD making it hard to identify their own hardware.
> 
> Sorry for the troubles <3

Great to hear that you found the source of the issue and thanks for posting the solution, It will certainly help other AMD users facing similar issues. I will add a reference to this issue in the README file as well.

**Comment by abdeladim-s** [comment]
> I would however like a feature that embeds the subtitles into the video, allowing us to download it afterwards (hopefully to get around the 200mb limit)
> 
> Or even just making a flag to disable it. Unless there is one?

You mean to merge the video with the subtitles directly ? without exporting just the srt file ?

**Comment by abdeladim-s** [comment]
Yeah the 200mb limit is imposed by the video component of streamlit, I tried to look for alternatives that support subtitles but unfortunaltey I couldn't find any! I will see if I there is any other solution. 
you can always use the CLI, it is easy and there is no limit!

**Comment by MidnightKittenCat** [comment]
Sounds great! Also is it possible to have multiple files in a queue?

**Comment by abdeladim-s** [comment]
Yes using the CLI, you can provide a text file containing the absolute path of the files, it will run them one by one,

**Comment by MidnightKittenCat** [comment]
A little update on this, seems only "whisper" by OpenAI and "whisper timestamped" detects rocm (cuda:0)

**Comment by abdeladim-s** [comment]
I've re-checked the device attribute of all models, I have fixed WhsiperX and hopefully it should be working now, please give it a try!
For fatser-whisper,  I am not sure if supports ROCm, because  the implementation is in C++ and they are not using Pytorch AFAIK.

**Comment by MidnightKittenCat** [comment]
For WhisperX, I'm getting this error:

`ValueError: unsupported device cuda:0
Traceback:
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/subsai/webui.py", line 523, in <module>
    run()
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/subsai/webui.py", line 516, in run
    webui()
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/subsai/webui.py", line 316, in webui
    subs = _transcribe(file_path, stt_model_name, model_config)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 194, in wrapper
    return cached_func(*args, **kwargs)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 223, in __call__
    return self._get_or_create_cached_value(args, kwargs)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 248, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 302, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/subsai/webui.py", line 189, in _transcribe
    model = subs_ai.create_model(model_name, model_config=model_config)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/subsai/main.py", line 95, in create_model
    return AVAILABLE_MODELS[model_name]['class'](model_config)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/subsai/models/whisperX_model.py", line 123, in __init__
    self.model = whisperx.load_model(self.model_type,
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/whisperx/asr.py", line 50, in load_model
    model = WhisperModel(whisper_arch,
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 120, in __init__
    self.model = ctranslate2.models.Whisper(`
    
    However it does say cuda:0 (which usually indicates that the gpu is detected)

**Comment by abdeladim-s** [comment]
Oh Yeah, WhisperX is using Faster-whisper as its backend! so I doubt if it will work in your case!

**Comment by MidnightKittenCat** [comment]
Ah that’s very unfortunate, thank you for trying though!



> > I would however like a feature that embeds the subtitles into the video, allowing us to download it afterwards (hopefully to get around the 200mb limit)
> > Or even just making a flag to disable it. Unless there is one?
> 
> You mean to merge the video with the subtitles directly ? without exporting just the srt file ?

And yes, I do mean this.

**Comment by abdeladim-s** [comment]
> Ah that’s very unfortunate, thank you for trying though!
> 
> > > I would however like a feature that embeds the subtitles into the video, allowing us to download it afterwards (hopefully to get around the 200mb limit)
> > > Or even just making a flag to disable it. Unless there is one?
> > 
> > 
> > You mean to merge the video with the subtitles directly ? without exporting just the srt file ?
> 
> And yes, I do mean this.

Ok, I've added this feature. 
If you are using the webui, you can find in the export section.
Please give it a try and let me know if you find any issues ?

**Comment by MidnightKittenCat** [comment]
> > Ah that’s very unfortunate, thank you for trying though!
> > > > I would however like a feature that embeds the subtitles into the video, allowing us to download it afterwards (hopefully to get around the 200mb limit)
> > > > Or even just making a flag to disable it. Unless there is one?
> > > 
> > > 
> > > You mean to merge the video with the subtitles directly ? without exporting just the srt file ?
> > 
> > 
> > And yes, I do mean this.
> 
> Ok, I've added this feature. If you are using the webui, you can find in the export section. Please give it a try and let me know if you find any issues ?

Very sorry I was very busy.

I'm now getting this error:

`Error: ffmpeg error (see stderr output for detail)
Traceback:
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/subsai/webui.py", line 535, in <module>
    run()
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/subsai/webui.py", line 528, in run
    webui()
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/subsai/webui.py", line 518, in webui
    exported_file_path = tools.merge_subs_with_video({subs_lang: subs}, str(media_file.resolve()), exported_video_filename)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/subsai/main.py", line 299, in merge_subs_with_video
    ffmpeg.run(output_ffmpeg)
File "/home/midnight/miniconda3/envs/caption/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)`

**Comment by MidnightKittenCat** [comment]
![image](https://github.com/abdeladim-s/subsai/assets/66114416/a8629cfd-483c-48e0-a145-ceed9c26bec1)
Hopefully this helps.

**Comment by MidnightKittenCat** [comment]
Could we also perhaps look into this? https://huggingface.co/facebook/nllb-200-3.3B

**Comment by abdeladim-s** [comment]
> ![image](https://user-images.githubusercontent.com/66114416/266388529-a8629cfd-483c-48e0-a145-ceed9c26bec1.png) Hopefully this helps.

Seems like FFmpeg cannot infer the encodec format of your video file. Are you perhaps applying the function on a an audio file ? if not could you please share a sample so I can test on my end ?

**Comment by MidnightKittenCat** [comment]
Very sorry something came up again, I seemed to of gotten it to work by using an mp4 this time.

When it comes to the 200mb limit, is this just for displaying the video itself? If so can we have an option that if the video is >200mb that it doesn’t embed it and only gives u the merge video with subtitles/download video button? Thanks!

**Comment by abdeladim-s** [comment]
@MidnightKittenCat, it is already the case I think, if the video exceeds 200mb you just can't view it, but you can transcribe and merge as well.

**Comment by MidnightKittenCat** [comment]
Finally got around to trying this for myself, this doesn't seem to be the case.\

> @MidnightKittenCat, it is already the case I think, if the video exceeds 200mb you just can't view it, but you can transcribe and merge as well.

"File must be 200.0MB or smaller." when inputting a file over 200mb, I was hopping it can be transcribed/merged without showing the video if >200mb

**Comment by matusnovak** [comment]
> I think Pytorch supports ROCm, so it should be supported out of the box basically, but I didn't test it so I couldn't tell. You can give it a try, and let me know how it goes :
> 
>     1. create a new virtual environment.
> 
>     2. install Pytorch ROCm compatible
> 
> 
> ```shell
> pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
> ```
> 
>     3. Then install `subsai` (as described in the README)

Thank you!

I had to use `rocm5.7` instead of `rocm5.4.2` and that did the trick for me on Manjaro Linux 6.2.16 with AMD Radeon 6800XT

**Comment by insberr** [comment]
I am getting `RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version`. I installed `pytorch` with `rocm6.0` and I have a `RX 6800`. I am also using the `m-bain/whisperX
` model. Any ideas on how to fix this?

**Comment by abdeladim-s** [comment]
> I am getting `RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version`. I installed `pytorch` with `rocm6.0` and I have a `RX 6800`. I am also using the `m-bain/whisperX ` model. Any ideas on how to fix this?

@insberr, maybe you should downgrade rocm to a lower version as I described in the comment before, `rocm5.7` worked for @matusnovak, so maybe try that one.

**Comment by aidan-gibson** [comment]
I also have an RX6800; the following setup worked for me:

`micromamba create -n whispergpu python="<3.12" pip`
`micromamba activate whispergpu`
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.1`
`pip install git+https://github.com/abdeladim-s/subsai`

**Comment by Snuupy** [comment]
There is now a fork of CTranslate2 that works with whisperX https://github.com/OpenNMT/CTranslate2/issues/1072#issuecomment-2271843277

Can this be included in subsai? @abdeladim-s

**Comment by abdeladim-s** [comment]
@Snuupy, Good to know that there is finally a fork that works for ROCm. 
From the [installation instructions](https://github.com/arlo-phoenix/CTranslate2-rocm/blob/rocm/README_ROCM.md) it doesn't seem straightforward to include it as a package in `subsai`'s dependencies, but you could give it a try. Just install the fork in the same virtual environment where `subsai` is installed—it should work.

**Comment by nutta-git** [comment]
Anyone else having issues with rocm7.0? 


`pip3 install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/rocm7.0`

Here is my python error log: 

```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1817, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/user/miniconda3/envs/subs/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 26, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 21, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/image_utils.py", line 59, in <module>
    from torchvision.transforms import InterpolationMode
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 163, in <module>
    @torch.library.register_fake("torchvision::nms")
AttributeError: module 'torch.library' has no attribute 'register_fake'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/subs/bin/subsai", line 3, in <module>
    from subsai.cli import main
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/subsai/__init__.py", line 1, in <module>
    from subsai.main import SubsAI, Tools
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/subsai/main.py", line 28, in <module>
    from subsai.configs import AVAILABLE_MODELS
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/subsai/configs.py", line 16, in <module>
    from subsai.models.hugging_face_model import HuggingFaceModel
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/subsai/models/hugging_face_model.py", line 15, in <module>
    from transformers import pipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1805, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1819, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
module 'torch.library' has no attribute 'register_fake'
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1817, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/user/miniconda3/envs/subs/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 26, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 21, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/image_utils.py", line 59, in <module>
    from torchvision.transforms import InterpolationMode
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 163, in <module>
    @torch.library.register_fake("torchvision::nms")
AttributeError: module 'torch.library' has no attribute 'register_fake'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/subs/bin/subsai", line 3, in <module>
    from subsai.cli import main
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/subsai/__init__.py", line 1, in <module>
    from subsai.main import SubsAI, Tools
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/subsai/main.py", line 28, in <module>
    from subsai.configs import AVAILABLE_MODELS
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/subsai/configs.py", line 16, in <module>
    from subsai.models.hugging_face_model import HuggingFaceModel
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/subsai/models/hugging_face_model.py", line 15, in <module>
    from transformers import pipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1805, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/user/miniconda3/envs/subs/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1819, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
module 'torch.library' has no attribute 'register_fake'

```

**Comment by nutta-git** [comment]
CTranslate2 has [merged](https://github.com/OpenNMT/CTranslate2/pull/1989 ) rocm support. 

I am not sure if subsai will work with the latest version of PyTorch.

**Comment by absadiki** [comment]
Thanks @nutta-git for the heads up!

Great to see CTranslate2 adding ROCm support.

Regarding PyTorch, I haven’t fully validated subsai against the latest versions, so compatibility may depend on the backend.

That said, with the ongoing work to make backends optional (via extras), this should get easier to manage. Once that’s merged, we’ll be in a better position to support and test different backend/version combinations independently, including newer PyTorch setups.
